name: Build and Compile Calculator

on:
    push:
        branches:      
            - main
jobs:  
    build:    
        runs-on: ubuntu-latest   
        
        steps:
            - name: Checkout Repository        
            uses: actions/checkout@v3   
            
            - name: Create bin folder
            run: mkdir bin
        
            - name: Compile Calculator 
            run: |         
                make 